name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.txt"
        # bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}